# Header
menu:
  Home: /
  Archives: /archives
  Categories: /
  Tags: /
  About: /
sidebar: true
description: "I'm a Dev"
social:
  github: floshodan
  mail: code@floshodan.io
  instagram: flo.shodan
# Post page
## Post_meta
post_meta_enable: true

post_author_enable: true
post_date_enable: true
post_category_enable: true

post_toc_enable: true
